# Generated by Django 4.2 on 2023-04-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_app', '0004_rename_day_name_institution_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'Datek', 'verbose_name_plural': 'Datki'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Instytucja', 'verbose_name_plural': 'Instytucje'},
        ),
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
